// Reconciles the committed knowledge corpus (content/knowledge/strudel.json,
// built by add-strudel-knowledge-corpus) into PATTERNS_DB (add-knowledge-store).
// Mirrors scripts/lib/patterns-manifest.mjs's toReconcileSql/buildReconcileSql
// split exactly: a pure SQL builder over already-parsed data, plus a thin
// file-reading wrapper — see design.md decisions 1-2.

import { readFileSync } from 'node:fs'
import { sq } from './patterns-manifest.mjs'

const DEFAULT_CORPUS_PATH = 'content/knowledge/strudel.json'

/**
 * SQL that brings `knowledge_chunks` (and its child tables) into exact
 * agreement with `chunks`. Idempotent in outcome: every chunk's row is
 * always re-upserted and its child rows always rebuilt from scratch,
 * the same non-diffing shape patterns' own reconcile uses (design.md's
 * note on "idempotent").
 *
 * @param {object[]} chunks the corpus file's `chunks` array
 * @returns {string}
 */
export function toKnowledgeReconcileSql(chunks) {
  const ids = chunks.map(c => c.id)
  const idList = ids.length > 0 ? ids.map(sq).join(', ') : '\'\''
  const lines = []

  lines.push('-- generated by scripts/lib/knowledge-store.mjs — do not edit by hand')

  for (const c of chunks) {
    lines.push(
      'INSERT INTO knowledge_chunks (id, kind, title, category, text, source_url, license, version) VALUES ('
      + `${sq(c.id)}, ${sq(c.kind)}, ${sq(c.title)}, ${sq(c.category)}, ${sq(c.text)}, ${sq(c.sourceUrl)}, ${sq(c.license)}, ${sq(c.version)})`
      + ' ON CONFLICT(id) DO UPDATE SET kind=excluded.kind, title=excluded.title, category=excluded.category, '
      + 'text=excluded.text, source_url=excluded.source_url, license=excluded.license, version=excluded.version;',
    )
  }

  if (ids.length > 0) {
    // Tags — same blanket delete + bulk re-insert shape pattern_tags uses.
    lines.push(`DELETE FROM knowledge_chunk_tags WHERE chunk_id IN (${idList});`)
    const tagRows = chunks.flatMap(c => (c.tags ?? []).map(t => `(${sq(c.id)}, ${sq(t)})`))
    if (tagRows.length > 0) lines.push(`INSERT INTO knowledge_chunk_tags (chunk_id, tag) VALUES ${tagRows.join(', ')};`)

    // Synonyms — function chunks only; concept/example chunks contribute none.
    lines.push(`DELETE FROM knowledge_chunk_synonyms WHERE chunk_id IN (${idList});`)
    const synonymRows = chunks.flatMap(c => (c.synonyms ?? []).map(s => `(${sq(c.id)}, ${sq(s)})`))
    if (synonymRows.length > 0) lines.push(`INSERT INTO knowledge_chunk_synonyms (chunk_id, synonym) VALUES ${synonymRows.join(', ')};`)

    // Params — position preserves declaration order.
    lines.push(`DELETE FROM knowledge_chunk_params WHERE chunk_id IN (${idList});`)
    const paramRows = chunks.flatMap(c => (c.params ?? []).map((p, i) =>
      `(${sq(c.id)}, ${i}, ${sq(p.name)}, ${sq(JSON.stringify(p.types ?? []))}, ${sq(p.description)})`))
    if (paramRows.length > 0) {
      lines.push(`INSERT INTO knowledge_chunk_params (chunk_id, position, name, types, description) VALUES ${paramRows.join(', ')};`)
    }

    // Examples — position preserves declaration order.
    lines.push(`DELETE FROM knowledge_chunk_examples WHERE chunk_id IN (${idList});`)
    const exampleRows = chunks.flatMap(c => (c.examples ?? []).map((code, i) => `(${sq(c.id)}, ${i}, ${sq(code)})`))
    if (exampleRows.length > 0) lines.push(`INSERT INTO knowledge_chunk_examples (chunk_id, position, code) VALUES ${exampleRows.join(', ')};`)
  }

  // Prune chunks (and their child rows) no longer in the corpus. Nothing
  // else ever writes these tables, so "not in the corpus" needs no
  // `origin`-style guard the way patterns' prune does.
  for (const table of ['knowledge_chunk_tags', 'knowledge_chunk_synonyms', 'knowledge_chunk_params', 'knowledge_chunk_examples']) {
    lines.push(`DELETE FROM ${table} WHERE chunk_id IN (SELECT id FROM knowledge_chunks WHERE id NOT IN (${idList}));`)
  }
  lines.push(`DELETE FROM knowledge_chunks WHERE id NOT IN (${idList});`)

  return `${lines.join('\n')}\n`
}

/** Reads and parses the committed corpus file. */
export function readCorpus(path = DEFAULT_CORPUS_PATH) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

/** read + parse + generate, in one call. */
export function buildKnowledgeReconcileSql(path = DEFAULT_CORPUS_PATH) {
  return toKnowledgeReconcileSql(readCorpus(path).chunks)
}
